-- The events table already has a unique constraint on (assignment_id, type)
-- defined in the initial migration. No additional constraint needed.
-- This migration file is kept for version control purposes.